### ISSUE TITLE
Adding versions that don't exist (name versus tag_name fields)

### ISSUE THREAD

**Issue by davidhicks** [konstin/github-wikidata-bot#11]
I noticed the edit at https://www.wikidata.org/w/index.php?title=Q28465648&diff=prev&oldid=629092034 adds version 3.6 to Transifex Client. Looking at the releases listed at official repository of the project (https://github.com/transifex/transifex-client/releases) I couldn't find version 3.6 listed. The bot may have extracted the version number from the "name" field in https://api.github.com/repos/transifex/transifex-client/releases rather than the "tag_name" field.

**Comment by konstin** [comment]
Yep, that's indeed the case; The bot currently prefers a version from release name over the release tag name. I'm not quite sure why I did choose name over tag, but I'll look into this.

**Comment by konstin** [comment]
I've changed the behavior to prefer the release tag name over the release name.
