### ISSUE TITLE
Bot not running anymore

### ISSUE THREAD

**Issue by Nudin** [konstin/github-wikidata-bot#12]
Hi,

the bot seems to be not running currently. The last run was on February 16th.

**Comment by konstin** [comment]
It's running again :)

Totally missed that because the cron job was not throwing any errors.

**Comment by Nudin** [comment]
Thanks! And just a tipp: I really like https://healthchecks.io for monitoring my cron jobs (especially for my backups it helps sleeping better). ;)

**Comment by konstin** [comment]
I've added healthchecks.io :)
