### ISSUE TITLE
Also add license

### ISSUE THREAD

**Issue by waldyrious** [konstin/github-wikidata-bot#22]
Github's API provides machine-readable license information that can be used to add that information to the Wikidata item in case it is missing.

**Comment by waldyrious** [comment]
Cross-referencing #15

**Comment by konstin** [comment]
That's a great idea! This could be done by querying the api ([example](https://api.github.com/repos/twbs/bootstrap)), translating the response with a github-license-to-wikidata-license table and then adding it as a new claim with the github repository page as source.

**Comment by Nudin** [comment]
Hi,
I started doing this with Openhup and Arch repos some time ago. The main issue is matching the license-strings you get from those APIs with the corresponding Wikidata-items.
But I just saw that with Github-API we are lucky – the API also contains the license SPDX-id which is unique and it set on Wikidata for most licenses. So we can use this for matching.
@waldyrious are you interested in implementing this?

**Comment by waldyrious** [comment]
> the API also contains the license SPDX-id which is unique and it set on Wikidata for most licenses. So we can use this for matching.

Yes, that's perfect :)

> @waldyrious are you interested in implementing this?

Sadly, I *am* interested, but I am completely overwhelmed with other commitments at the moment :(
