### ISSUE TITLE
Support Edit groups

### ISSUE THREAD

**Issue by Nudin** [konstin/github-wikidata-bot#51]
[Edit groups](https://www.wikidata.org/wiki/Wikidata:Edit_groups) allow to undo an bunch of edits at once. Since it's very annoying and time-consuming to revert edits by the bot if something went wrong, I think it would be nice to support Edit groups.
[Support can be added easily](https://www.wikidata.org/wiki/Wikidata:Edit_groups).

We just ne to think if we want to use one edit-group per run or one edit-group per run and software or even both (if possible).

**Comment by nichtich** [comment]
Please support a method to stop the bot until this is fixed because it otherwise spams the edit history.

**Comment by Nudin** [comment]
> Please support a method to stop the bot until this is fixed because it otherwise spams the edit history.

Edit groups have nothing to do with the edit history. They are only an external tool to quickly undo a big number of edits.
If there are problems with the bot you can already blacklist items.
