### ISSUE TITLE
Official website differs only in protocol

### ISSUE THREAD

**Issue by tacsipacsi** [konstin/github-wikidata-bot#67]
Your bot repeatedly [adds](https://www.wikidata.org/w/index.php?title=Q306398&diff=780506370) statement with HTTP website, while the exact same domain is already there, the only difference is the bot’s version uses insecure HTTP protocol. It should be checked before, just like in #65.

**Comment by konstin** [comment]
While this definitely shouldn't happen, it's unfortunately not as easy as saying that `www.openbve-project.net` and `openbve-project.net` are identical as they don't have to be (I know cases where e.g. can't reach the server with or without http and there was one case where the non-www version had a different redirect). What I've done is that I'm requesting the url to check whether there are redirects, and if there are, I use the redirect instead; This way only the https url is added.

**Comment by tacsipacsi** [comment]
Thanks for the patch. It fixes the problem on this very item, as openBVE’s HTTP website redirects to HTTPS. However, many sites do not, so the two versions live independently (but with the same content). I think we can be bold enough to think that if an HTTPS version with the exact same domain and path is already added, it’s really the same—someone hopefully checked it before adding, and we risk just not adding useful information, not deleting or modifying anything in the wrong way. (Some additional, independent logging may be introduced, so that they can be checked manually.)

**Comment by konstin** [comment]
Yeah that seems like a good idea. Do you have an example of where there's a https version but the non-redirecting http version on the github page?

**Comment by Nudin** [comment]
I agree with tacsipacsi. I also saw at least one example for this with the github-wiki-bot. We shouldn't add an URL if the same modulo normalization already exists. The normalization should not only cover http<->https but also tailing slashes and probably even 'www.'-subdomains.
