### ISSUE TITLE
Omit patch/minor releases

### ISSUE THREAD

**Issue by nichtich** [konstin/github-wikidata-bot#94]
With continuous integration it is possible to have a very frequent release cycle resulting in dozens of releases. Please add a method to omit patch versions or minor versions, for instance by respecting a regular expression that versions must match to be included.

**Comment by Nudin** [comment]
There's no rule about what versions items should have or should not have. And since the Wikipedia-Infoboxes use the version form Wikidata and want to be up2date we always need to have the current version, even if it is a minor version.
Due to this I don't see any easy solution to this.

**Comment by nichtich** [comment]
The easy solution to this is extension of https://www.wikidata.org/wiki/User:Github-wiki-bot/Exceptions to include only selected versions, e.g.:

    Q67641976: ^[0-9]\.[0-9]$

would only add  Q67641976's releases if their version number matches the regular expression `^[0-9]\.[0-9]$`.

**Comment by Nudin** [comment]
This doesn't solve the general problems: we won't have the current version in Wikidata and therefor show an outdated version in Wikipedia and all other sites.
Can you give an example of an item where you see an problem? And what is the issue with it?

**Comment by nichtich** [comment]
Thanks for reply, having the current version is an important requirement indeed. I was quite shocked by the history when the bot detects a software item for the first time but. If it further annoys me I'll reopen or do a pull request.

**Comment by Nudin** [comment]
One improvement to have less edits in edit history and watch-lists would be to do one edit only per added version, instead of currently 4 edits. But this is (was?) blocked by limitations of pywikibot.
