### ISSUE TITLE
Exclude claims with deprecated rank

### ISSUE THREAD

**Issue by konstin** [konstin/github-wikidata-bot#96]
Originally from the [talk page](https://www.wikidata.org/wiki/User_talk:Konstin#Github-wiki-bot_should_not_touch_deprecated_version_ranks):

> See for example: https://www.wikidata.org/wiki/Q6542725. There are version items 1 2 3 4, which are outdated and precede normal versioning schema. The bot marks 4 as the latest version which is incorrect: https://www.wikidata.org/w/index.php?title=Q6542725&type=revision&diff=991216806&oldid=991216805. This (and other cases with changed versioning schema, where new versions compare less than older versions) can be/is solved by setting deprecated rank to the old versions. The bot thus should leave deprecated ranks untouched (while it could still update statuses, references and other information). --AMDmi3 (talk) 15:00, 26 August 2019 (UTC)

**Comment by Nudin** [comment]
94697c258a5a243c41c159b6ac64a996713a3050 should fix this.

**Comment by konstin** [comment]
Thank you!
